// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.dspace.orm.entity;

import org.dspace.orm.entity.Bi4Dis;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Bi4Dis_Roo_Configurable {
    
    declare @type: Bi4Dis: @Configurable;
    
}
