// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.dspace.orm.entity;

import org.dspace.orm.entity.Communities2item;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Communities2item_Roo_Configurable {
    
    declare @type: Communities2item: @Configurable;
    
}
