// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.dspace.orm.model;

import org.dspace.orm.model.Bundle;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Bundle_Roo_Configurable {
    
    declare @type: Bundle: @Configurable;
    
}
