// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.dspace.orm.model;

import org.dspace.orm.model.Epersongroup2workspaceitem;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Epersongroup2workspaceitem_Roo_Configurable {
    
    declare @type: Epersongroup2workspaceitem: @Configurable;
    
}
